### ISSUE TITLE
About the model folder

### ISSUE THREAD

**Issue by wangjg33** [cswry/OSEDiff#11]
Hello. Great job。
May I ask what has been added to [autoencoder_kl.py](https://github.com/cswry/OSEDiff/blob/main/models/autoencoder_kl.py)  and ([unet_2d_condition.py](https://github.com/cswry/OSEDiff/blob/main/models/unet_2d_condition.py)) in the models folder compared to Diffusers.

**Comment by cswry** [comment]
Hello, we add merge_lora function in these two files.
