### ISSUE TITLE
Whether release training code or not?

### ISSUE THREAD

**Issue by zzzzzuber** [cswry/OSEDiff#13]
Thanks for your wonderful work!!!
The balance of effectiveness and efficiency of OSEDiff is very shocked!!! 
I trained our network with vsd loss, but maybe my training code have some difference with you, the results are terrible, so would you release training code in the future?
Hope your reply!

**Comment by ChenhLiwnl** [comment]
same terrible results:(

**Comment by cswry** [comment]
Thank you for your interest. However, we're not currently planning to open-source our training codes in the short term.

**Comment by zzzzzuber** [comment]
> Have you tried not using vsd loss, only using lpips loss. First, make sure this step is correct
I'll try, thanks~

**Comment by zzzzzuber** [comment]
> Thank you for your interest. However, we're not currently planning to open-source our training codes in the short term.

ok, Thanks for your reply~
