### ISSUE TITLE
questions about the output.

### ISSUE THREAD

**Issue by TT-T1** [cswry/OSEDiff#16]
Hello, I'm sorry to bother you. When I use landscape or flower images, there is no output result.

For human images, the colors of the eyes and lips become vivid. Is there any way to adjust this?
![Capture](https://github.com/cswry/OSEDiff/assets/54735213/ef433208-5907-41dd-8a36-6dfdf4946b24)
![Capture2](https://github.com/cswry/OSEDiff/assets/54735213/2f3d5c2e-0cce-48ea-8a04-d0687ed8046c)

**Comment by ZhenyanSun** [comment]
> Hello, I'm sorry to bother you. When I use landscape or flower images, there is no output result.
> 
> For human images, the colors of the eyes and lips become vivid. Is there any way to adjust this? ![Capture](https://private-user-images.githubusercontent.com/54735213/346866833-ef433208-5907-41dd-8a36-6dfdf4946b24.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNTMwNjAsIm5iZiI6MTcyMTM1Mjc2MCwicGF0aCI6Ii81NDczNTIxMy8zNDY4NjY4MzMtZWY0MzMyMDgtNTkwNy00MWRkLThhMzYtNmRmZGY0OTQ2YjI0LlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDAxMzI0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwNmY1Y2VjMmY3NDIzMWZiM2UwMTQyNzQwN2JiOTVlYWIwZDdkOTEyZjA5ZTJlZDA3YzM2YTc3NDFmMGM5YjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lFXSJe_OZ_BewA6AKMHRAbmln1X8oI4NUAqkpb4Rrbg) ![Capture2](https://private-user-images.githubusercontent.com/54735213/346866920-2f3d5c2e-0cce-48ea-8a04-d0687ed8046c.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNTMwNjAsIm5iZiI6MTcyMTM1Mjc2MCwicGF0aCI6Ii81NDczNTIxMy8zNDY4NjY5MjAtMmYzZDVjMmUtMGNjZS00OGVhLThhMDQtZDA2ODdlZDgwNDZjLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDAxMzI0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyYTdhMzk5NWE0YTRjYmE2YzY1ZTNlYWFmYzRlZjdjZmQ5YWRhNTExMTczMTFmNWE1ZWViMzJhOGVmZjQwYmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KBCq5wo-APSRbxI_09KI5hjDwyGdgD8JdB1zd7wa54M)

HI TT-T1，can you share some experiences？Thank you very much.
