### ISSUE TITLE
We noticed that some images become more colorful and vibrant after being processed by OSEDiff. Is this a controllable option?

### ISSUE THREAD

**Issue by ch3nboyu** [cswry/OSEDiff#49]
and we  want to know if the model supports adjusting fidelity like SeeSR

**Comment by ch3nboyu** [comment]
Thank you 🥰

**Comment by laolongboy** [comment]
> and we want to know if the model supports adjusting fidelity like SeeSR

Hi, how to adjust fidelity in SeeSR? higher controlnet scale?

**Comment by ch3nboyu** [comment]
U can see https://github.com/cswry/SeeSR/blob/main/asserts/hyp.md 🤗

**Comment by laolongboy** [comment]
> Your observation is sharp, the current version of OSEDiff has the issue you mentioned: oversaturation after processing. Unfortunately, OSEDiff does not currently support functionality like SeeSR for adjusting fidelity and perception, which is a very important feature. Our recent work, PiSA-SR, addresses this issue. If you're interested, please refer to [this](https://arxiv.org/pdf/2412.03017).

I read the "PiSA-SR". Maybe we can directly use classifier score distillation instead of VSD in osediff?  Have you tried it? Any findings?
