### ISSUE TITLE
Question: Is the time step directly fixed to T in the input of diffusion (the largest time step)

### ISSUE THREAD

**Issue by Feynman1999** [cswry/OSEDiff#5]
Is the time step directly fixed to T in the input of diffusion (the largest time step)

**Comment by cswry** [comment]
yes

**Comment by Feynman1999** [comment]
Have you ever tried ablation experiments on the setting of t. Intuitively, an LR contains a lot more information than xt when T=1000. Is it because of the presence of Lora weight that T becomes less critical?

**Comment by Feynman1999** [comment]
Can you share your understanding of time step settings， thanks!!

**Comment by cswry** [comment]
Hi, A larger T tends to generate more, while a smaller T tends to preserve fidelity. 

T balances fidelity and perception. We aim for the better generation performance of OSEDiff, so we chose 999.

**Comment by cswry** [comment]
> Have you ever tried ablation experiments on the setting of t. Intuitively, an LR contains a lot more information than xt when T=1000. Is it because of the presence of Lora weight that T becomes less critical?



> Have you ever tried ablation experiments on the setting of t. Intuitively, an LR contains a lot more information than xt when T=1000. Is it because of the presence of Lora weight that T becomes less critical?

Your judgment is correct. Setting different T values at the input of UNet only affects the convergence speed, with little impact on the final model performance.
