### ISSUE TITLE
How to discard text prompt as in ablation study?

### ISSUE THREAD

**Issue by ShawnXu10** [cswry/OSEDiff#51]
Hi,

In the ablation study you mentioned, you indicated an experiment conducted without employing text prompts. I would like to inquire about the specific implementation of this approach. Did you simply replace text with empty content, or did you modify the model to function without the text prompt feature? If you could provide details on how you implemented this, it would be greatly appreciated.

Thank you for your time and consideration.

**Comment by lrfnb** [comment]
My guess is that the samples are directly replaced with empty content. Many previous T2I models did this.

**Comment by ShawnXu10** [comment]
> My guess is that the samples are directly replaced with empty content. Many previous T2I models did this.

Another problem will be that the Lreg is depend on text prompt during training. Did they remove the Lreg or just input an empty content anyway. Lreg doesn't make much sense with just empty content, does it?

**Comment by cswry** [comment]
Hello, sorry for the confusion. Not using text prompts means we don’t include tag text as positive prompts during training, and the negative prompts for Lreg are set to empty.

**Comment by xiangyuxu0815** [comment]
> Hello, sorry for the confusion. Not using text prompts means we don’t include tag text as positive prompts during training, and the negative prompts for Lreg are set to empty.

Thanks for your response.
