### ISSUE TITLE
Output results not as good as SeeSR?

### ISSUE THREAD

**Issue by AIisCool** [cswry/OSEDiff#9]
Thought the output should be better, or at least the same but faster? Tried with many images that I tested SeeSR with and all results with OSEDiff are worse. :(

Input:
![image](https://github.com/cswry/OSEDiff/assets/92149242/fd6aa3d4-3444-4c77-8134-5f7d6bdf9d12)

SeeSR: (Using SD-Turbo)
![image](https://github.com/cswry/OSEDiff/assets/92149242/cf51eb95-7462-467e-9d9a-5c6ea3bf6abf)

OSEDiff:
![Star Trek Ds9 - 6x13 - Far Beyond The Stars x264 ac3 03](https://github.com/cswry/OSEDiff/assets/92149242/927935f6-702c-418f-8f2e-e88d0a3fd583)
Facial details are not very good and texture of the wall is gone. Only the gray part of the outfit is much better. Not sure why it isn't as good?

Thank you for your hard work on this, just not understanding why it isn't as good as SeeSR. It is faster however!

**Comment by cswry** [comment]
Hello, please inference with tiled function if the image size exceeds set dimensions. 

We have added this function.

**Comment by AIisCool** [comment]
@cswry Hi, I have tried again. Results are a bit better, however the wall behind the person has lost the detail? Face is also not as good? Sorry to report back with these results.

![Star Trek Ds9 - 6x13 - Far Beyond The Stars x264 ac3 03](https://github.com/cswry/OSEDiff/assets/92149242/a4b3d4d0-df4b-49f4-9e28-cc7a719422bc)

**Comment by cswry** [comment]
Your observation is keen, and OSEDiff indeed has these issues at this stage. 

Overall it has achieved an effect comparable to SeeSR's 50-step generation. You can observe more cases.

**Comment by AIisCool** [comment]
> OSEDiff indeed has these issues at this stage.

I hope it can be improved and surpass SeeSR! Please don't think I'm saying OSEDiff is "bad". I've seen areas/details that it can be better at restoring than SeeSR. Both are clearly projects with a lot of hard work and dedication put into them.
